const tableColumn = [
  { label: '#', type: 'index', fixed: true },
  { label: '产品名称', prop: 'productName', disableSort: true, width: 100 },
  { label: '二维码', prop: 'qrCode', disableSort: true, width: 120 },
  { label: '产品编号', prop: 'productNo', disableSort: true, width: 100 },
  { label: '检测总结果', prop: 'qrCode', disableSort: true, width: 100 },
  { label: '加工机床编号', prop: 'qrCode', disableSort: true, width: 120 },
  { label: 'R1', prop: 'detect01', disableSort: true, minWidth: 100 }, // 01
  { label: 'R2', prop: 'detect02', disableSort: true, minWidth: 100 },
  { label: 'LTA_a5', prop: 'detect03', disableSort: true, minWidth: 100 },
  { label: 'LTA_a21', prop: 'detect04', disableSort: true, minWidth: 100 },
  { label: 'LTA_a23', prop: 'detect05', disableSort: true, minWidth: 100 },
  { label: 'LTA_a24', prop: 'detect06', disableSort: true, minWidth: 100 },
  { label: 'LTA_a22', prop: 'detect07', disableSort: true, minWidth: 100 },
  { label: 'LTA_a6', prop: 'detect08', disableSort: true, minWidth: 100 }, // 08
  { label: 'LTA_a3', prop: 'detect09', disableSort: true, minWidth: 100 },
  { label: 'LTA_a7', prop: 'detect10', disableSort: true, minWidth: 100 },
  { label: 'LTA_a8', prop: 'detect11', disableSort: true, minWidth: 100 },
  { label: 'LTA_a4', prop: 'detect12', disableSort: true, minWidth: 100 }, // 12
  { label: '尺寸1041', prop: 'detect13', disableSort: true, minWidth: 120 },
  { label: '尺寸209', prop: 'detect14', disableSort: true, minWidth: 100 },
  { label: '尺寸42', prop: 'detect15', disableSort: true, minWidth: 100 },
  { label: 'detect16', prop: 'detect16', disableSort: true }, // 16
  { label: 'detect17', prop: 'detect17', disableSort: true },
  { label: 'detect18', prop: 'detect18', disableSort: true },
  { label: 'detect19', prop: 'detect19', disableSort: true },
  { label: 'detect20', prop: 'detect20', disableSort: true },
  { label: 'detect21', prop: 'detect21', disableSort: true },
  { label: 'detect22', prop: 'detect22', disableSort: true },
  { label: 'detect23', prop: 'detect23', disableSort: true }, // 上面保留
  { label: 'LTA_a3真圆度', prop: 'detect24', disableSort: true, width: 120 },
  { label: 'LTA_a7真圆度', prop: 'detect25', disableSort: true, width: 120 },
  { label: 'LTA_a8真圆度', prop: 'detect26', disableSort: true, width: 120 },
  { label: 'LTA_a4真圆度', prop: 'detect27', disableSort: true, width: 120 },
  { label: 'detect28', prop: 'detect28', disableSort: true }, // 此条保留
  { label: 'TM投影点01', prop: 'detect29', disableSort: true, width: 120 }, // 29 - 54
  { label: 'TM投影点02', prop: 'detect30', disableSort: true, width: 120 },
  { label: 'TM投影点03', prop: 'detect31', disableSort: true, width: 120 },
  { label: 'TM投影点04', prop: 'detect32', disableSort: true, width: 120 },
  { label: 'TM投影点05', prop: 'detect33', disableSort: true, width: 120 },
  { label: 'TM投影点06', prop: 'detect34', disableSort: true, width: 120 },
  { label: 'TM投影点07', prop: 'detect35', disableSort: true, width: 120 },
  { label: 'TM投影点08', prop: 'detect36', disableSort: true, width: 120 },
  { label: 'TM投影点09', prop: 'detect37', disableSort: true, width: 120 },
  { label: 'TM投影点10', prop: 'detect38', disableSort: true, width: 120 },
  { label: 'TM投影点11', prop: 'detect39', disableSort: true, width: 120 },
  { label: 'TM投影点12', prop: 'detect40', disableSort: true, width: 120 },
  { label: 'TM投影点13', prop: 'detect41', disableSort: true, width: 120 },
  { label: 'TM投影点14', prop: 'detect42', disableSort: true, width: 120 },
  { label: 'TM投影点15', prop: 'detect43', disableSort: true, width: 120 },
  { label: 'TM投影点16', prop: 'detect44', disableSort: true, width: 120 },
  { label: 'TM投影点17', prop: 'detect45', disableSort: true, width: 120 },
  { label: 'TM投影点18', prop: 'detect46', disableSort: true, width: 120 },
  { label: 'TM投影点19', prop: 'detect47', disableSort: true, width: 120 },
  { label: 'TM投影点20', prop: 'detect48', disableSort: true, width: 120 },
  { label: 'TM投影点21', prop: 'detect49', disableSort: true, width: 120 },
  { label: 'TM投影点22', prop: 'detect50', disableSort: true, width: 120 },
  { label: 'TM投影点23', prop: 'detect51', disableSort: true, width: 120 },
  { label: 'TM投影点24', prop: 'detect52', disableSort: true, width: 120 },
  { label: 'TM投影点25', prop: 'detect53', disableSort: true, width: 120 },
  { label: 'TM投影点26', prop: 'detect54', disableSort: true, width: 120 },
  { label: '测针测量点01', prop: 'detect55', disableSort: true, width: 120 }, // 55 - 66
  { label: '测针测量点02', prop: 'detect56', disableSort: true, width: 120 },
  { label: '测针测量点03', prop: 'detect57', disableSort: true, width: 120 },
  { label: '测针测量点04', prop: 'detect58', disableSort: true, width: 120 },
  { label: '测针测量点05', prop: 'detect59', disableSort: true, width: 120 },
  { label: '测针测量点06', prop: 'detect60', disableSort: true, width: 120 },
  { label: '测针测量点07', prop: 'detect61', disableSort: true, width: 120 },
  { label: '测针测量点08', prop: 'detect62', disableSort: true, width: 120 },
  { label: '测针测量点09', prop: 'detect63', disableSort: true, width: 120 },
  { label: '测针测量点10', prop: 'detect64', disableSort: true, width: 120 },
  { label: '测针测量点11', prop: 'detect65', disableSort: true, width: 120 },
  { label: '测针测量点12', prop: 'detect66', disableSort: true, width: 120 }
]

export default tableColumn
